/*
SQLyog Ultimate v12.08 (64 bit)
MySQL - 5.6.24 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

create table `t_role_menu` (
	`role_id` bigint (20),
	`menu_id` bigint (20)
); 
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','2');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','28');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','29');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','31');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','32');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','33');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','34');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','55');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','35');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','36');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','38');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','39');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','40');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','41');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','56');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','42');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','43');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','45');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','46');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','47');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','48');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','57');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','49');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','50');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','51');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','52');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','53');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','54');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','5');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','7');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','11');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','12');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','13');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','16');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','9');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','20');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','21');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','22');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','10');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','23');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','24');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','25');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','6');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','26');
insert into `t_role_menu` (`role_id`, `menu_id`) values('2','27');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','1');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','58');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','59');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','2');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','28');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','29');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','31');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','32');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','33');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','34');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','55');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','35');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','36');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','38');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','39');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','40');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','41');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','56');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','42');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','43');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','45');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','46');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','47');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','48');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','57');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','49');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','50');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','51');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','52');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','53');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','54');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','3');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','60');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','61');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','4');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','5');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','7');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','11');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','12');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','13');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','14');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','15');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','16');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','8');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','17');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','18');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','19');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','9');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','20');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','21');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','22');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','10');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','23');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','24');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','25');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','6');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','26');
insert into `t_role_menu` (`role_id`, `menu_id`) values('1','27');
